In [ ]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt:

import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('global_ads_performance_dataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'global_ads_performance_dataset.csv'

In [ ]:
df.head()        # shows first 5 rows — check column names, data types
df.info()        # shows column types and missing values
df.describe()    # shows basic stats (mean, min, max) for numeric columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1800 non-null   object
 1   platform       1800 non-null   object
 2   campaign_type  1800 non-null   object
 3   industry       1800 non-null   object
 4   country        1800 non-null   object
 5   impressions    1800 non-null   int64
 6   clicks         1800 non-null   int64
 7   CTR            1800 non-null   float64
 8   CPC            1800 non-null   float64
 9   ad_spend       1800 non-null   float64
 10  conversions    1800 non-null   int64
 11  CPA            1800 non-null   float64
 12  revenue        1800 non-null   float64
 13  ROAS           1800 non-null   float64
dtypes: float64(6), int64(3), object(5)
memory usage: 197.0+ KB

,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
count,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
mean,102919.018889,3962.675556,0.038427,1.572756,6171.527272,181.562222,46.608961,30101.850450,6.450367
std,55740.900690,2941.858037,0.017082,0.800872,5776.996958,171.424239,41.185556,34560.032941,6.590986
min,5059.000000,91.000000,0.008900,0.280000,58.000000,2.000000,4.800000,142.690000,0.130000
25%,54948.000000,1678.000000,0.025400,0.950000,1966.587500,59.000000,20.202500,7275.757500,2.170000
50%,103653.000000,3318.000000,0.035550,1.460000,4393.860000,130.000000,33.375000,18362.965000,4.295000
75%,150470.250000,5628.000000,0.049800,2.050000,8455.830000,252.250000,56.812500,38963.385000,8.212500
max,199650.000000,16660.000000,0.095600,3.950000,38453.320000,1151.000000,335.860000,295028.260000,49.000000

In [ ]:
df.head()

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
0,2024-01-21,Google Ads,Search,Fintech,UAE,59886,2113,0.0353,1.26,2662.38,159,16.74,4803.43,1.80
1,2024-01-22,TikTok Ads,Search,EdTech,UK,135608,5220,0.0385,1.18,6159.60,411,14.99,64126.68,10.41
2,2024-06-15,TikTok Ads,Video,Healthcare,USA,92313,5991,0.0649,0.85,5092.35,267,19.07,10489.07,2.06
3,2024-01-02,TikTok Ads,Shopping,SaaS,Germany,83953,5935,0.0707,1.32,7834.20,296,26.47,50505.07,6.45
4,2024-02-22,TikTok Ads,Search,Healthcare,UK,91807,4489,0.0489,1.93,8663.77,107,80.97,3369.53,0.39

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1800 non-null   object
 1   platform       1800 non-null   object
 2   campaign_type  1800 non-null   object
 3   industry       1800 non-null   object
 4   country        1800 non-null   object
 5   impressions    1800 non-null   int64
 6   clicks         1800 non-null   int64
 7   CTR            1800 non-null   float64
 8   CPC            1800 non-null   float64
 9   ad_spend       1800 non-null   float64
 10  conversions    1800 non-null   int64
 11  CPA            1800 non-null   float64
 12  revenue        1800 non-null   float64
 13  ROAS           1800 non-null   float64
dtypes: float64(6), int64(3), object(5)
memory usage: 197.0+ KB

In [ ]:
df.describe()

,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
count,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
mean,102919.018889,3962.675556,0.038427,1.572756,6171.527272,181.562222,46.608961,30101.850450,6.450367
std,55740.900690,2941.858037,0.017082,0.800872,5776.996958,171.424239,41.185556,34560.032941,6.590986
min,5059.000000,91.000000,0.008900,0.280000,58.000000,2.000000,4.800000,142.690000,0.130000
25%,54948.000000,1678.000000,0.025400,0.950000,1966.587500,59.000000,20.202500,7275.757500,2.170000
50%,103653.000000,3318.000000,0.035550,1.460000,4393.860000,130.000000,33.375000,18362.965000,4.295000
75%,150470.250000,5628.000000,0.049800,2.050000,8455.830000,252.250000,56.812500,38963.385000,8.212500
max,199650.000000,16660.000000,0.095600,3.950000,38453.320000,1151.000000,335.860000,295028.260000,49.000000

In [ ]:
df.isnull().sum()

date             0
platform         0
campaign_type    0
industry         0
country          0
impressions      0
clicks           0
CTR              0
CPC              0
ad_spend         0
conversions      0
CPA              0
revenue          0
ROAS             0
dtype: int64

In [ ]:
df['CTR'] = df['clicks'] / df['impressions']

In [ ]:
df['CPC'] = df['ad_spend'] / df['clicks']

In [ ]:
df['CVR'] = df['conversions'] / df['clicks']
channel_summary = df.groupby('platform')[['CTR', 'CPC', 'CPA', 'CVR', 'ROAS']].mean()
print(channel_summary)

                 CTR       CPC        CPA       CVR      ROAS
platform
Google Ads  0.039847  2.149069  64.064653  0.045250  4.113028
Meta Ads    0.024973  1.316095  39.096921  0.044847  6.915730
TikTok Ads  0.054953  1.009978  29.196711  0.046168  9.538600

In [ ]:
channel_summary_sorted = channel_summary.sort_values('ROAS', ascending=False)
print(channel_summary_sorted)

                 CTR       CPC        CPA       CVR      ROAS
platform
TikTok Ads  0.054953  1.009978  29.196711  0.046168  9.538600
Meta Ads    0.024973  1.316095  39.096921  0.044847  6.915730
Google Ads  0.039847  2.149069  64.064653  0.045250  4.113028

In [ ]:
channel_summary_sorted = channel_summary.sort_values('ROAS', ascending=False)
print(channel_summary_sorted)

                 CTR       CPC        CPA       CVR      ROAS
platform
TikTok Ads  0.054953  1.009978  29.196711  0.046168  9.538600
Meta Ads    0.024973  1.316095  39.096921  0.044847  6.915730
Google Ads  0.039847  2.149069  64.064653  0.045250  4.113028

In [ ]:
best_roas = channel_summary_sorted['ROAS'].iloc[0]
worst_roas = channel_summary_sorted['ROAS'].iloc[-1]
multiplier = best_roas / worst_roas
print(f"Best channel has {multiplier:.1f}x higher ROAS than worst channel")

Best channel has 2.3x higher ROAS than worst channel

In [ ]:
import pandas as pd

df = pd.read_csv('global_ads_performance_dataset.csv')
df['CTR'] = df['clicks'] / df['impressions']
df['CPC'] = df['ad_spend'] / df['clicks']

platform_summary = df.groupby('platform')[['CTR', 'CPC', 'CPA', 'ROAS']].mean()
print(platform_summary)

platform_summary_sorted = platform_summary.sort_values('ROAS', ascending=False)
print(platform_summary_sorted)

best_roas = platform_summary_sorted['ROAS'].iloc[0]
worst_roas = platform_summary_sorted['ROAS'].iloc[-1]
multiplier = best_roas / worst_roas
print(f"Best platform has {multiplier:.1f}x higher ROAS than worst platform")

FileNotFoundError: [Errno 2] No such file or directory: 'global_ads_performance_dataset.csv'

In [ ]:
import pandas as pd

df = pd.read_csv('global_ads_performance_dataset.csv')
df['CTR'] = df['clicks'] / df['impressions']
df['CPC'] = df['ad_spend'] / df['clicks']

platform_summary = df.groupby('platform')[['CTR', 'CPC', 'CPA', 'ROAS']].mean()
print(platform_summary)

platform_summary_sorted = platform_summary.sort_values('ROAS', ascending=False)
print(platform_summary_sorted)

best_roas = platform_summary_sorted['ROAS'].iloc[0]
worst_roas = platform_summary_sorted['ROAS'].iloc[-1]
multiplier = best_roas / worst_roas
print(f"Best platform has {multiplier:.1f}x higher ROAS than worst platform")

                 CTR       CPC        CPA      ROAS
platform
Google Ads  0.039847  2.149069  64.064653  4.113028
Meta Ads    0.024973  1.316095  39.096921  6.915730
TikTok Ads  0.054953  1.009978  29.196711  9.538600
                 CTR       CPC        CPA      ROAS
platform
TikTok Ads  0.054953  1.009978  29.196711  9.538600
Meta Ads    0.024973  1.316095  39.096921  6.915730
Google Ads  0.039847  2.149069  64.064653  4.113028
Best platform has 2.3x higher ROAS than worst platform

In [ ]:
total_impressions = df['impressions'].sum()
total_clicks = df['clicks'].sum()
total_conversions = df['conversions'].sum()

click_dropoff = 1 - (total_clicks / total_impressions)
conversion_dropoff = 1 - (total_conversions / total_clicks)

print(f"Drop-off from impression to click: {click_dropoff:.1%}")
print(f"Drop-off from click to conversion: {conversion_dropoff:.1%}")

Drop-off from impression to click: 96.1%
Drop-off from click to conversion: 95.4%

In [ ]:
print(platform_summary_sorted[['CPA']])

                  CPA
platform
TikTok Ads  29.196711
Meta Ads    39.096921
Google Ads  64.064653

In [ ]:
platform_campaign = df.groupby(['platform', 'campaign_type'])['ROAS'].mean().sort_values(ascending=False)
print(platform_campaign)

NameError: name 'df' is not defined

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving global_ads_performance_dataset.csv to global_ads_performance_dataset.csv

In [ ]:
import pandas as pd

df = pd.read_csv('global_ads_performance_dataset.csv')
df['CTR'] = df['clicks'] / df['impressions']
df['CPC'] = df['ad_spend'] / df['clicks']
df['CVR'] = df['conversions'] / df['clicks']

platform_campaign = df.groupby(['platform', 'campaign_type'])['ROAS'].mean().sort_values(ascending=False)
print(platform_campaign)

platform    campaign_type
TikTok Ads  Search           10.519280
            Display          10.036931
            Video             9.572286
            Shopping          8.055798
Meta Ads    Display           7.270138
            Search            6.902312
            Shopping          6.767500
            Video             6.761030
Google Ads  Search            4.790885
            Video             4.141828
            Shopping          3.753631
            Display           3.681264
Name: ROAS, dtype: float64

In [ ]:
industry_summary = df.groupby('industry')['ROAS'].mean().sort_values(ascending=False)
print(industry_summary)

industry
EdTech        6.828952
SaaS          6.647973
Healthcare    6.587989
E-commerce    6.133524
Fintech       6.031357
Name: ROAS, dtype: float64

In [ ]:
country_summary = df.groupby('country')['ROAS'].mean().sort_values(ascending=False)
print(country_summary)

country
UAE          6.962054
Germany      6.709647
Australia    6.674526
India        6.649732
Canada       6.258015
UK           6.145038
USA          5.809173
Name: ROAS, dtype: float64

In [ ]:
country_platform_matrix = df.groupby(['country', 'platform'])['ROAS'].mean().unstack()
print(country_platform_matrix)

platform   Google Ads  Meta Ads  TikTok Ads
country
Australia    3.936019  8.003919   10.014364
Canada       3.591262  6.164943   10.185417
Germany      3.840851  7.469688    9.735846
India        4.017500  6.674494    9.945658
UAE          4.767851  8.777895    9.052131
UK           4.508247  5.891574    9.196557
USA          4.010755  6.137400    8.439333

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving global_ads_performance_dataset.csv to global_ads_performance_dataset.csv

In [ ]:
import pandas as pd

df = pd.read_csv('global_ads_performance_dataset.csv')
df['CTR'] = df['clicks'] / df['impressions']
df['CPC'] = df['ad_spend'] / df['clicks']
df['CVR'] = df['conversions'] / df['clicks']

average_roas = df['ROAS'].mean()
print(f"Average ROAS: {average_roas:.2f}")

NameError: name 'df' is not defined